language: java
notifications:
  hipchat:
    rooms:
      secure: LhlTbdNGSBncacJGPzL581Ld8w1JXyZ7GM4SFp7GGiPSkwX8d2t5cK8/BgY7viX2mjbdYaqT3wt+IUUQTRjuYyQaM2rHmqvZnnvz+vEqoye9cDGvzF3eV4CLuX1LTD4fui+cz0Kq4TucHuof4hd2Fk0eArk8tqqrQMZEiypnaakuTh0Kq/0DfJwk1GYbQAW+4swyL0+ETz9yrz3tg01aHS324b9DkGrwnSbDxzUmCeUqFVl3hcaXit40JFo55xxad6fImhL0vm1VHKPu83tri+bfuPfTJgQV8iwoOKgA8iQocRG6tzjpomG2tv8k9EDv2YbFmAhFfNSmxiBPtreZi9HBeSGn5dnm14zXP7KSihAgMrRVKyxH+8H/RbFDmyqEwqvP4r7CNzl0YKxZ6VB64zc2+QPNjjiyWazdl1yKA5bD+glmH4nZdm5UPPEMEZCcUzMnVxldBKQ9IEZ0Z3YvjN1qZ7hwSiGVlxrz3neDbukjU++OZO7vYxCCLib0tU72XDxF6giqg07uE4BMSSpEhn7S7kmiDrj0B1Z+gPHcuZSjgmyn4XMhFkQzhQNnmld0A+eATNxSxWRCFMpLyqoYf/pb1hFW356yDSCZZcgLXEuBN9qYNx1bhfGnTOsqEehi8iXtOOsDVo5GX+vIQop0N077Pa7V70nmWJSa1zmmn6I=
deploy:
  provider: releases
  api_key:
    secure: iNDRtQ9F95+3c8+znu2UF1FK7LPM4LI+VWmJR4XTl+fND20lchf9qkdD3C2zL0+RLOYt8sKrykcVkebDx+z6j2rNvCj8ZTYiHrgn2xPilTHZUOSqAHc/Kqx+LgewTka1x8qx7VYGAoChUvU0t61VRy/izjGGMkQhKWq2zj3mu+JhiJo753mK3faiA2/593LnrlvnbQy44fG7oZVxRwPQxdiqoUGY+Pz3EMYxZFGm8q1s7Aiv3JAxbwqenJKOMMTYRGtmRaYIFOHxow2PJAfk6wZsgVX1jqJmmQ5G/43h9eaWJg+E+XYb4erfbD8cHQJ0BKZmK6x6TcWKLK5jNLAYeRpJk8l05nzkfEEWjiABF9oLDS7wGhWC/EzfMIlCLtu5W0dpGta0AOAFRQNiS0UDfOEh/o8a3HmA4IQqNH9woaMbqnKS1r+dHVk18042r9Ne+eU7PdrUIEM9+AjJRLCvrZrvb/Lp6hLM6bkiDxwhhnR0iz6wN2Xc5k0h406U2zVlDrvsMSWFdgdKjSEO/gnYwANsnCNN1gaN2oNlS+JFg9v931ccN1rpKsE3fdD/MtkkT2WGINoMAX0NwdFnh2C8yILv+lpgRcmRTlio412BNrBJTZofazdeSN+hJqlO+aMoBGZTGvN+dLhjHmsYBBiiMvvqZZIaHPfH43g9Z9atKEA=
  file: build/libs/xlr-travisci-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-travisci-plugin
